blank_issues_enabled: false
contact_links:
  - name: Pucham Support
    url: https://pucham.in/support/telegram-group
    about: Reach out to our Support team if you encounter any difficulties with accessing your Pucham directory.
