name: Enhance Existing Content
description: Suggest improvements to the content in an existing article.
labels:
  - content
body:
  - type: markdown
    attributes:
      value: |
        **Pucham Contributors!!** This is the MyIndianHub/pucham open source repository. If you want to suggest improvements to the content, please open an issue here.

        * For any questions, feel free to discuss in the [Discussions](https://github.com/MyIndianHub/pucham/discussions).
        * Before filing an issue, please review the [Contributing Guide](https://github.com/MyIndianHub/pucham/blob/main/CONTRIBUTING.md).
        * Check if a similar [issue](https://github.com/MyIndianHub/pucham/issues) has already been opened.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project adheres to a Code of Conduct, and all contributors are expected to read and follow it.
      options:
        - label: I have read and agree to the Pucham project's [Code of Conduct](https://github.com/MyIndianHub/pucham/blob/main/CODE_OF_CONDUCT.md)
          required: true

  - type: textarea
    attributes:
      label: Which article on docs.pucham.com is affected?
      description: Please provide a link to the article you'd like to see updated.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What part(s) of the article would you like to see updated?
      description: |
        - Provide detailed information to help us understand the change you're suggesting.
        - Explain why the docs should be updated, and include any relevant use cases.
        - Specify the expected outcome or behavior.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: |
        - Can you reliably reproduce the issue? How frequently does it occur, and how many users are affected?
        - Include any additional context or screenshots related to the suggested enhancement.
    validations:
      required: false
