name: Greeting Workflow

on:
  pull_request:
    types:
      - opened

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Send Greeting
      run: |
        echo "👋 Welcome to the collaboration space! 🚀"
        echo "Thank you for opening a pull request. Your contribution is valued!"
      shell: bash
